<?php
    //get total items in cart
    $_cartQty = $this->getSummaryCount();
    if(empty($_cartQty)) {
        $_cartQty = 0;
    }

    $_cartTotal = $this->helper('checkout/cart')->getQuote()->getGrandTotal(); //get total price
    if(empty($_cartQty)) {
        $_cartTotal = 0;
    }
    $formattedPrice = Mage::helper('core')->currency($_cartTotal, true, false);
?>

<a id="shopping-menu" data-target-element="#header-cart">
    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
    <span class="item-cart">
	    <?php echo '( ' ?><strong><span class="count"><?php echo $_cartQty ?></span></strong><?php echo ' )' ?>
	    <span class="item-grand-total"><?php echo $formattedPrice; ?></span>
    </span>
    <span class="shopping-arrow"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i></span>
    <span class="shopping-arrow-down"><i class="fa fa-arrow-circle-down" aria-hidden="true"></i></span>
</a> 

<div id="header-cart" class="block-cart skip-content">
    <?php echo $this->getChildHtml('minicart_content');?>
</div>
