<?php
/**
 * Header Template
 *
 * Description:
 * - overriden from rwd default
 * - add category search
 *
 */

$catalogSearchHelper =  $this->helper('catalogsearch');
?>

<?php
    $category = Mage::getModel('catalog/category');
    if(is_object(Mage::registry('current_category'))){
        $currentCategoryPath=Mage::registry('current_category')->getPathIds();
    }else{
        $currentCategoryPath = array();
    }
    $category->load(Mage::app()->getStore()->getRootCategoryId());
    $childrenString = $category->getChildren();
    $children = explode(',',$childrenString);
    $categoryOptions='';
    foreach($children as $c){
        if($this->getRequest()->getParam('cat')!=""){
            $selected = ($this->getRequest()->getParam('cat')==$c)?'SELECTED':'';    
        }
        else{
            $selected = '';
        }
    $categoryOptions.= '<option value="' . $c . '" ' . $selected . '>' . $category->load($c)->getName() . '</option>' . "\n";
    }
?>

<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
    <div class="input-box">
        <select name="cat" id="cat">
            <option value="">All Categories</option>
            <?php echo $categoryOptions ?>
        </select>
        <label for="search"><?php echo $this->__('Search:') ?></label>
        <input id="search" type="search" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text required-entry" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" placeholder="<?php echo $this->__('Type what you are looking for') ?>" />
        
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button search-button"><span><i class="fa fa-search"></i>&nbsp;</button>
    </div>

    <div id="search_autocomplete" class="search-autocomplete"></div>
    <script type="text/javascript">
    //<![CDATA[
        var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
        searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
    //]]>
    </script>
</form>
