
<?php 
    $storeId = Mage::app()->getStore()->getStoreId();
    $rootCategoryId = Mage::app()->getStore($storeId)->getRootCategoryId();
    $category = Mage::getModel('catalog/category')
    ->getCollection()
    ->setStoreId($storeId)
    ->addFieldToFilter('is_active', 1)
    ->addAttributeToFilter('path', array('like' => "1/{$rootCategoryId}/%"))
    ->addAttributeToFilter('url_key', $this->getData('url_key'))
    ->addAttributeToSelect('*')
    ->getFirstItem();
    if($category->getId()!= NULL){
        $_products = Mage::getResourceModel('catalog/product_collection')
        ->addAttributeToSelect('*')
        ->addCategoryFilter($category)
        ->addAttributeToSort('position')
        ->setPageSize(12);
    }    

    $_taxHelper = $this->helper('tax');
?>

<?php if (isset($_products) && count($_products)): ?>
<?php $_products->addAttributeToSelect('name')->addAttributeToSelect('short_description')->addAttributeToSelect('small_image')->addAttributeToSelect('price')->addAttributeToSelect('special_price')->addAttributeToSelect('group_price'); ?>
<div class="subtitle page-title">
    <h2><a href="<?php echo $category->getUrl(); ?>"><?php echo $category->getName(); ?> </a></h2> 
    
</div>
<?php $_columnCount = $this->getColumnCount(); ?>
    <span class="product-slide-nav">
        <a class="btn prev">&nbsp;</a>
        <a class="btn next">&nbsp;</a>
    </span>
    <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col animate-list product-list-slide">
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>
            <?php /*if ($i++%$_columnCount==0): ?>
            <?php endif*/ ?>
            <?php
                $productId=$_product->getId();
                $productShortDesc=Mage::getResourceModel('catalog/product')->getAttributeRawValue($productId, 'short_description', $storeId);
                $productName=Mage::getResourceModel('catalog/product')->getAttributeRawValue($productId, 'name', $storeId);
            ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> invisible" data-id="<?php echo $_product->getId(); ?>" data-category="<?php echo $_product->getCategoryId(); ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 210; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
                <div class="product-info">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                        <?php echo $productName;?>
                    </a></h2>
                    <?php
                    // Provides extra blocks on which to hang some features for products in the list
                    // Features providing UI elements targeting this block will display directly below the product name
                    if ($this->getChild('name.after')) {
                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                            $_nameAfterChild->setProduct($_product);
                            echo $_nameAfterChild->toHtml();
                        }
                    }
                    ?>
                    <div class="product_sku">Kode:<?php echo $_product->getSku(); ?></div>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>
                <div class="actions">
                    <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                        <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
            </li>
            <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            <?php endif*/ ?>
        <?php endforeach ?>
    </ul>
<?php endif; ?>
